### PR TITLE
Warning & deprecations 

### PR DESCRIPTION
**Pull request by ghost**
fixed few minor warnings

### CODE REVIEW

**Comment by yeleleo** [comment]
@entotsu are you alive?

**Comment by takuoka** [comment]
wow

**Comment by takuoka** [comment]
@yeleleo Thank you for your comment 🙏 
This PR is confricting... 💧 

Now, I invited you to this repo. 👍 
Feel free to edit this codes if you want 👌

**Comment by ghost** [comment]
> This PR is confricting... 💧

Well, it's rude.

PR isn't much, but imo it's better remove all the warnings and deprecations. I wish some thankful user of my open source projects could do at least such minor improvements to the code as matter of saying thank you and keeping the code up to date with latest frameworks.

**Pull request closed without merging**
